# These are supported funding model platforms

github: [Mauricio-100, gopu-inc] # Remplace par ton username GitHub
patreon: Mauricio-100 # Remplace par ton username Patreon
open_collective: Mauricio-100 # Remplace par ton nom Open Collective
ko_fi: Mauricio-100 # Remplace par ton username Ko-fi
tidelift: npm/mauricio-10 # Pour Tidelift
community_bridge: mauricio-100 # Remplace par ton nom de projet
liberapay: mauricio-100 # Remplace par ton username Liberapay
issuehunt: mauricio-100 # Remplace par ton username IssueHunt
lfx_crowdfunding: mauricio-100 # Remplace par ton nom de projet
polar: mauricio-100 # Remplace par ton username Polar
buy_me_a_coffee: mauricio-100 # Remplace par ton username Buy Me a Coffee
thanks_dev: mauricio-100 # Remplace par ton username thanks.dev
custom: ['https://xnycggrc.mychariow.market', 'https://chariow.com/sponsor', 'https://patreon.com/chariow'] # URLs personnalisées
